const $=id=>document.getElementById(id),money=n=>'£'+n.toFixed(2);
function art([x,y,w,h],label=''){const s=document.createElement('span');s.className='sprite';s.style.aspectRatio=w+'/'+h;const i=document.createElement('img');i.src='menu.png';i.alt=label;i.style.width=(1888/w*100)+'%';i.style.left=(-x/w*100)+'%';i.style.top=(-y/h*100)+'%';i.draggable=false;s.append(i);return s}
const data={protein:[['Chicken breast',10.5,[72,248,171,265],'Lean, flame-grilled with a smoky finish.'],['Chicken thigh',10.5,[270,248,173,265],'Juicy, chargrilled with golden, smoky edges.'],['Steak',12.9,[470,245,171,268],'Grilled, seasoned and sliced with sea salt.'],['Secreto Ibérico',12.5,[663,248,173,265],'Tender, rich and full of chargrilled flavour.'],['Halloumi',11.9,[178,519,185,268],'Grilled with a golden, crispy crust. Vegetarian.'],['Falafel',9.5,[376,519,179,268],'Crispy outside with a soft, herby centre. Vegan.'],['Tofu',9.5,[573,519,179,268],'Golden-seared with a delicate, crispy edge. Vegan.']],side:[['Salad mix',0,[265,859,120,152],'Fresh & crisp. Vegetarian, gluten free. Vegan upon request.'],['Sourdough bread',0,[391,859,150,152],'Warm & crusty. Vegan.'],['Lemon quinoa',0,[551,859,124,152],'Zesty & fresh. Gluten free.']],sauce:[['Lemon & herb',0,[81,1073,112,108],'Cool & zesty. Vegetarian, gluten free.'],['Hot honey piri piri',0,[203,1073,134,108],'Sweet & spicy.'],['Harissa',0,[352,1073,108,108],'Smoky & spicy. Vegan, gluten free.'],['Chimichurri',0,[475,1073,109,108],'Fresh & herby. Vegan, gluten free.'],['Tahini',0,[594,1073,114,108],'Creamy & nutty. Vegan, gluten free.'],['Beetroot ketchup',0,[720,1073,139,108],'Earthy & tangy. Vegan, gluten free.']],starter:[['Chupadedo olives',2.9,[1057,196,162,280],'Marinated with garlic and fresh herbs. Vegan, gluten free.'],['Signature sweet potato fries',7.5,[1238,196,192,280],'Crispy, golden and served with homemade dips. Vegetarian, gluten free. Vegan upon request.'],['Falafel bites, tahini & chimichurri',6.9,[1430,196,210,280],'Crispy bites with tahini and fresh chimichurri. Vegan, gluten free.'],['Homemade hummus',5.9,[1648,196,171,280],'Silky, creamy with warm, fragrant spices. Vegan.'],['Sourdough bread + choice of dip',3.9,[1138,482,196,280],'Crusty pieces served with your choice of dip. Vegan.'],['Grilled halloumi + dip',6.9,[1349,482,178,280],'Golden grilled pieces with your choice of dip. Vegetarian, gluten free.'],['Vegetable crisps',3.9,[1532,482,196,280],'Light, crunchy selection of crisp vegetables. Vegan, gluten free.']],sweet:[['Banana bread',4.9,[1080,925,205,196],'Soft, moist with a caramelised banana top. Vegetarian, gluten free.'],['Basque cheesecake',5.9,[1308,925,215,196],'Rich, creamy with burnt exterior. Vegetarian, gluten free.']]};
[['logo',[40,20,80,37],'era.'],['plateTitle',[244,98,456,82],'Create your plate. 1 protein + 2 sides + 1 sauce.'],['proteinTitle',[357,201,229,44],'01 Start with protein'],['sideTitle',[380,798,182,43],'02 Add two sides'],['sauceTitle',[412,1010,115,43],'Sauces'],['starterTitle',[1233,130,361,52],'Starters & sharers'],['sweetTitle',[1282,832,264,64],'Something sweet']].forEach(([id,box,label])=>$(id).append(art(box,label)));
let selection={protein:null,side:[],sauce:null},cart=[];let toastTimer;
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function select(kind,index){if(!data[kind]||!Number.isInteger(index)||!data[kind][index])throw Error('Invalid menu selection');if(kind==='side'){if(selection.side.includes(index))selection.side=selection.side.filter(n=>n!==index);else if(selection.side.length<2)selection.side.push(index);else{toast('Choose up to two sides. Tap a selected side to change it.');return}}else selection[kind]=selection[kind]===index?null:index;renderSelection()}
function renderSelection(){document.querySelectorAll('[data-kind]').forEach(b=>{const k=b.dataset.kind,i=+b.dataset.index;b.setAttribute('aria-pressed',k==='side'?selection.side.includes(i):selection[k]===i)});const ready=selection.protein!==null&&selection.side.length===2&&selection.sauce!==null;$('addPlate').disabled=!ready;$('progress').textContent=selection.protein===null?'Choose your protein':selection.side.length<2?`Choose ${2-selection.side.length} ${selection.side.length?'more side':'sides'}`:selection.sauce===null?'Choose your sauce':'Your plate is ready';$('addPlate').textContent='Add plate'+(selection.protein!==null?' · '+money(data.protein[selection.protein][1]):'')}
function add(name,price,detail=''){cart.push({name,price,detail});renderCart();toast(name+' added')}
for(const [kind,id] of [['protein','proteins'],['side','sides'],['sauce','sauces'],['starter','starters'],['sweet','sweets']])data[kind].forEach((item,index)=>{const b=document.createElement('button');b.className='card';b.setAttribute('aria-label',`${item[0]}${item[1]?' '+money(item[1]):''}. ${item[3]}`);b.append(art(item[2]));if(['protein','side','sauce'].includes(kind)){b.dataset.kind=kind;b.dataset.index=index;b.setAttribute('aria-pressed','false');b.onclick=()=>select(kind,index)}else b.onclick=()=>kind==='starter'&&(index===4||index===5)?chooseDip(item,index===5):add(item[0],item[1]);$(id).append(b)});
const coming=art([1550,942,203,159],'With more to come. Something sweet…');coming.classList.add('coming');$('sweets').append(coming);
data.protein.forEach((p,i)=>{const price=[6.9,6.9,7.9,7.9,6.9,5.9,5.9][i],b=document.createElement('button');b.innerHTML=`<span>${p[0]}</span><b>${money(price)} +</b>`;b.onclick=()=>add('Extra '+p[0],price);$('extraProteins').append(b)});
['Lemon & herb','Hot honey piri piri','Harissa','Chimichurri','Tahini','Falafel','Beetroot ketchup'].forEach(n=>{const b=document.createElement('button');b.textContent=n+' +';b.onclick=()=>add('Extra '+n,1.9);$('extraSauces').append(b)});
$('addPlate').onclick=()=>{if($('addPlate').disabled)return;const p=data.protein[selection.protein];add(p[0]+' plate',p[1],selection.side.map(i=>data.side[i][0]).join(' + ')+' · '+data.sauce[selection.sauce][0]);selection={protein:null,side:[],sauce:null};renderSelection()};
function renderCart(){const total=cart.reduce((n,x)=>n+x.price,0);$('count').textContent=cart.length;$('orderbar').hidden=!cart.length;$('barText').textContent=cart.length+' '+(cart.length===1?'item':'items')+' in your order';$('total').textContent=money(total);$('dialogTotal').textContent=money(total);$('lines').replaceChildren();if(!cart.length)$('lines').textContent='Your order is empty. Choose a plate or something to share.';cart.forEach((item,i)=>{const el=document.createElement('div');el.className='line';const content=document.createElement('div');const name=document.createElement('strong');name.textContent=item.name;content.append(name);if(item.detail){const detail=document.createElement('small');detail.textContent=item.detail;content.append(detail)}const remove=document.createElement('button');remove.className='remove';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+item.name);remove.onclick=()=>{cart.splice(i,1);renderCart();const next=$('lines').querySelectorAll('.remove');(next[Math.min(i,next.length-1)]||$('done')).focus({preventScroll:true})};content.append(remove);const price=document.createElement('strong');price.textContent=money(item.price);el.append(content,price);$('lines').append(el)})}
for(const id of ['review','reviewTop'])$(id).onclick=()=>{openDialog($('order'))};for(const id of ['close','done'])$(id).onclick=()=>$('order').close();renderCart();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_plate',description:'Select a protein, two distinct sides and a sauce. Stages a plate without adding it to the order.',inputSchema:{type:'object',properties:{protein:{type:'string'},sides:{type:'array',items:{type:'string'},minItems:2,maxItems:2},sauce:{type:'string'}},required:['protein','sides','sauce'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const p=data.protein.findIndex(x=>x[0]===input.protein),s=data.sauce.findIndex(x=>x[0]===input.sauce),sides=Array.isArray(input.sides)?input.sides.map(n=>data.side.findIndex(x=>x[0]===n)):[];if(p<0||s<0||sides.length!==2||sides.some(i=>i<0)||new Set(sides).size!==2)throw Error('Choose valid menu names and two distinct sides.');selection={protein:p,side:sides,sauce:s};renderSelection();return{ready:true,price:data.protein[p][1]}}})).catch(()=>{})}catch{}}

function chooseDip(item,doubleAvailable){const d=document.createElement('dialog');d.innerHTML=`<form method="dialog"><div class="dialogHead"><h2>Choose your dip</h2><button value="cancel" aria-label="Cancel">×</button></div><p>${item[0]}</p><label for="dip">Dip</label><select id="dip" required><option value="">Choose a sauce</option>${data.sauce.map(x=>`<option>${x[0]}</option>`).join('')}</select>${doubleAvailable?'<label class="double"><input id="double" type="checkbox"> Double portion + £3.90</label>':''}<button class="confirmDip" value="add">Add to order</button></form>`;document.body.append(d);d.querySelector('[value="cancel"]').formNoValidate=true;d.addEventListener('close',()=>{if(d.returnValue==='add'){const doubled=d.querySelector('#double')?.checked;add(item[0],item[1]+(doubled?3.9:0),d.querySelector('#dip').value+(doubled?' · Double portion':''))}d.remove()});openDialog(d)}

function openDialog(dialog){
  const trigger=document.activeElement;
  if(!dialog.dataset.dismissReady){
    dialog.dataset.dismissReady='true';
    let startedOutside=false;
    const outside=e=>{const r=dialog.getBoundingClientRect();return e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)};
    dialog.addEventListener('pointerdown',e=>{startedOutside=outside(e)});
    dialog.addEventListener('click',e=>{if(startedOutside&&outside(e))dialog.close();startedOutside=false});
  }
  dialog.addEventListener('close',()=>{if(trigger?.isConnected)trigger.focus({preventScroll:true})},{once:true});
  dialog.showModal();
}
